
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personalhelper
    username: root
    password: isaac170302
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true