apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: caregiver
  name: caregiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caregiver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: caregiver
    spec:
      containers:
      - image: 146038/caregiver
        name: caregiver
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: caregiver
  name: caregiver
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: caregiver
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: caregiver
  name: caregiver
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: caregiver
  type: ClusterIP
status:
  loadBalancer: {}
